### ISSUE TITLE
fail2ban-server won't start when a logfile does not exist

### ISSUE THREAD

**Issue by HaleyACS** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#10]
FYI - when configuring fail2ban jails - and activating one jail that actually provides no logfile to check (ion my case, I have no apache running, had however activated it), fail2ban won't start.
Same happens when owncloud logfile path is wrong.

Once the wrong entries fixed, it works.

Eventually you should put that into the Docs.
Cheers

**Comment by ryecoaaron** [comment]
closing due to age.
