### ISSUE TITLE
OMV 3.x support 

### ISSUE THREAD

**Issue by happyreacer** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#11]
It is a must have for a omv 3.x 
I know omx3 is beta but many other plugins are avalible.

**Comment by ryecoaaron** [comment]
OMV 3.x isn't anywhere near stable and is changing a lot right now.  I'm sure fail2ban will be ported but give it time...

Part of porting plugins to OMV 3.x is trying the 2.x version on 3.x to determine what needs to be changed.  Have you done that?

**Comment by happyreacer** [comment]
No, sorry. I don't have enough know for these.

**Comment by prbond** [comment]
See master-omv3
