### ISSUE TITLE
error param bantime into mkconf/fail2ban

### ISSUE THREAD

**Issue by vpistis** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#20]
Hi,

into file `/usr/share/openmediavault/mkconf/fail2ban` the parameter `bintime` is incorrectly `binime`.

Thanx for this superb plugin :)

Ciao
Valentino

**Comment by ryecoaaron** [comment]
Fix in commit 9d048839483e31bdfd76fc8d8445f75837a97b76
