### ISSUE TITLE
Problem found in ...mkconf/fail2ban

### ISSUE THREAD

**Issue by adamnagy1** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#22]
Hello,
I think there is a typo in the [config script](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-fail2ban/blob/master/usr/share/openmediavault/mkconf/fail2ban), in the line 44 and 45:
` -v "concat('fintime = ',findtime)" -n`
` -v "concat('banime = ',bantime)" -n`
I guess it should be findtime and bantime. In addition usedns is missing from the script and so from the config file. It's not a big issue but puts warning lines into the log:
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'findtime' not defined in 'ssh'. Using default one: 600`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'usedns' not defined in 'ssh'. Using default one: 'warn'`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'findtime' not defined in 'ssh-ddos'. Using default one: 600`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'usedns' not defined in 'ssh-ddos'. Using default one: 'warn'`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'findtime' not defined in 'apache-noscript'. Using default one: 600`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'usedns' not defined in 'apache-noscript'. Using default one: 'warn'`
`Oct 22 14:04:46 mynas fail2ban[14654]: WARNING 'findtime' not defined in 'apache-404'. Using default one: 600`
I hope that this helps improving the code.
 Adam

**Comment by ryecoaaron** [comment]
This plugin currently doesn't have a maintainer.  Feel free to submit pull requests if you are able to test if they work.

**Comment by ryecoaaron** [comment]
This was fixed in commit 9d048839483e31bdfd76fc8d8445f75837a97b76
