### ISSUE TITLE
How to fill the action items

### ISSUE THREAD

**Issue by johnzhang2015-zz** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#24]
Hi, thanks first for your plugin, here I have a question on how to use it.

on item action items, there must be fill in something, but there is no clearly indicate about it, it only display:
"action_= ban only / action_mw=ban & send an email / action_mwl=ban & send an email with whois report and log lines."

Could anyone help to clear how to fill it on the item?

thanks!

**Comment by ryecoaaron** [comment]
You will probably have better luck getting feedback on the forum.  Not many people see the issues for plugins and even though I maintain the plugin, I don't use fail2ban.
