### ISSUE TITLE
[OMV6] Not a number 

### ISSUE THREAD

**Issue by snowy-night-light** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#29]
Getting error when trying to change max retry. Probably caused by getting raw string from input and not converting it into a number.

![image](https://user-images.githubusercontent.com/33985207/141166518-9daad7c3-c0aa-4800-9cbc-3c116139fea9.png)

**Comment by ryecoaaron** [comment]
Fixed in 6.0.1 in the repo now.
