### ISSUE TITLE
[OMV6] After editing first jail you cannot edit the others

### ISSUE THREAD

**Issue by snowy-night-light** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#30]
The bug appears in OMV6 web GUI in the "Jails" tab.

Steps:
1. Edit the first jail.
2. Try editing any other jail.
3. When you click edit button it will show information regarding the first jail you edited not the one you selected to edit now.

**Comment by ryecoaaron** [comment]
This should be fixed in OMV 6.0.2.

**Comment by snowy-night-light** [comment]
> This should be fixed in OMV 6.0.2.

The issue is indeed fixed in 6.0.2. Closing.
