### ISSUE TITLE
fail by compiling

### ISSUE THREAD

**Issue by voicenoise** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#34]
Hello
I try it to install on a Odroid N2 with OMV 4.1.36-1
Linux Kernel 4.9.277 Debian (Buster but not shure)

i got the following error by
`$ fakeroot debian/rules clean binary`

```
$ home/openmediavault-fail2ban# fakeroot debian/rules clean binary
dh clean
dh: Sorry, but 11 is the highest compatibility level supported by this debhelper.
debian/rules:4: recipe for target 'clean' failed
make: *** [clean] Error 25
```

has anyone a idea to solve this?
Thanks

edit:
now found this .deb files
https://mirrors.lengjingyun.com/OpenMediaVault/openmediavault-plugin-developers/pool/main/o/openmediavault-fail2ban/

Are these safe?

**Comment by ryecoaaron** [comment]
Why are you trying to compile instead of installing omv-extras and just installing from the plugin list?

**Comment by ryecoaaron** [comment]
It also looks like you are trying to compile the omv6 code on omv5.

**Comment by voicenoise** [comment]
i need the afp share, thats a reason why i am still on version 4.
I've now installed fail2ban natively as you can't manage fail2ban the way I want with the plugin.

appreciate for helping
