### ISSUE TITLE
[OMV 6.0.42-2] Missing Fail2ban under Diagnostic tab

### ISSUE THREAD

**Issue by Giovany86** [OpenMediaVault-Plugin-Developers/openmediavault-fail2ban#35]
Hello there. 
After upgrading to OMV 6.0.42-2 (Was on OMV 5.5.X previously) i am missing fail2ban plugin informations under "Diagnostic -> Services" where on the previous version was listed the info about the plugin (Banned IP, Ban count, etc).

Behavior can be reproduced by upgrading to OMV 6 inside a VM.
Already tried to uninstall & Reinstall the plugin, the issue still persist.

Under "services" tab, i'm only able to configure the plugin and not view any info about it.

PS : This is my first time using Github, i don't know if i'm in the right place x)

**Comment by ryecoaaron** [comment]
You are in the correct place and I will have to see if I can create that in 6.x.  I missed it when porting.

**Comment by ryecoaaron** [comment]
6.0.3 in the repo now.
